import cv2
import numpy as np

class ImageGenerator:
    def __init__(self, img_height: int, img_width: int, rgb: bool, save_path: str) -> None:
        self.height = img_height
        self.width = img_width
        self.rgb = rgb
        self.save_path = save_path

    def generate(self) -> None:
        if self.rgb:
            img = np.random.randint(255, size=(self.width, self.height, 3), dtype=np.uint8)
        else:
            img = np.random.randint(255, size=(self.width, self.height), dtype=np.uint8)
        cv2.putText(img ,"@ Generated by Nikita Sidelnikov",
                    (int(self.width * 0.01), self.height - 20), cv2.FONT_HERSHEY_SIMPLEX, 
                    0.5, (0, 0, 0), 2, cv2.LINE_8)
        cv2.imwrite(self.save_path + "/img.png", img)
